Add launch command with arn or roleName option
dtan4/ec2c pull request #10
Opened 2016-10-27 10:47 UTC by koudaiii

2016-10-28 02:02 UTC, dtan4 commented
Is this really pass to all cases?

- specify neither ARN nor IAM Role Name
- specify ARN only
- specify IAM Role Name only
- specify both ARN and IAM Role Name

2016-10-28 10:00 UTC, koudaiii commented
- [x] specify neither ARN nor IAM Role Name

```
ec2c launch \
       --ami $AMI_ID \
       --publicip \
       --az $AVAILABILITY_ZONE \
       --type $INSTANCE_TYPE \
       --key $SSH_KEY_NAME \
       --sg $SECURITY_GROUPS \
       --subnet $SUBNET_ID \
       --userData ./user-data \
       --volumeSize $VOLUME_SIZE \

===> Successfully launched! Instance ID: i-
```
ok,create instance.

- [x] specify ARN only

```
ec2c launch \
       --ami $AMI_ID \
       --publicip \
       --az $AVAILABILITY_ZONE \
       --type $INSTANCE_TYPE \
       --key $SSH_KEY_NAME \
       --sg $SECURITY_GROUPS \
       --subnet $SUBNET_ID \
       --userData ./user-data \
       --volumeSize $VOLUME_SIZE \
       --arn $ARN \
===> Successfully launched! Instance ID: i-
```

ok, create instance.

- [x] specify IAM Role Name only
```
ec2c launch \
       --ami $AMI_ID \
       --publicip \
       --az $AVAILABILITY_ZONE \
       --type $INSTANCE_TYPE \
       --key $SSH_KEY_NAME \
       --sg $SECURITY_GROUPS \
       --subnet $SUBNET_ID \
       --userData ./user-data \
       --volumeSize $VOLUME_SIZE \
       --roleName $ROLE_NAME \
===> Successfully launched! Instance ID: i-
```

ok. create instance.

- [x] specify both ARN and IAM Role Name => Not Supported

```
ec2c launch \
       --ami $AMI_ID \
       --publicip \
       --az $AVAILABILITY_ZONE \
       --type $INSTANCE_TYPE \
       --key $SSH_KEY_NAME \
       --sg $SECURITY_GROUPS \
       --subnet $SUBNET_ID \
       --userData ./user-data \
       --volumeSize $VOLUME_SIZE \
       --roleName $ROLE_NAME \
       --arn $ARN \
```

```
panic: InvalidParameterCombination: The parameter 'iamInstanceProfile.name' may not be used in combination with 'iamInstanceProfile.arn'
	status code: 400, request id: fdd5a2c1-8498-439a-a4d9-78927e04b813
```

I added validate check.

```
InvalidParameterCombination: The parameter 'roleName' and 'arn' can not be used in combination
```

plz review 🏹

2016-11-01 01:05 UTC, dtan4 requested changes

2016-11-01 01:05 UTC, dtan4 commented on command/launch.go
> +		fmt.Fprintln(os.Stderr, "InvalidParameterCombination: The parameter 'roleName' and 'arn' can not be used in combination")
Is this message copied from original error of aws-sdk-go?
If so, please show it as it is.

```go
fmt.Fprintln(os.Stderr, err)
return 1
```

(Of course, I have to treat all other errors as well as this...)

2016-11-01 06:59 UTC, koudaiii commented on command/launch.go
> +		fmt.Fprintln(os.Stderr, "InvalidParameterCombination: The parameter 'roleName' and 'arn' can not be used in combination")
I see :) I will try it :) Thank you!!

2016-11-02 02:17 UTC, koudaiii commented on command/launch.go
> +		fmt.Fprintln(os.Stderr, "InvalidParameterCombination: The parameter 'roleName' and 'arn' can not be used in combination")
https://github.com/dtan4/ec2c/pull/10/files#diff-0380a26c6fb593cb2283592d0ba604d4R127

Already display error message. 👀 

Change "panic" to "return 1" will be next PR.

2016-11-02 02:58 UTC, dtan4 requested changes

2016-11-02 02:58 UTC, dtan4 commented on command/launch.go
> +	flags.StringVar(&arn, "arn", "", "ARN")
Please explain in detail what ARN is...

2016-11-02 04:52 UTC, koudaiii commented on command/launch.go
> +	flags.StringVar(&arn, "arn", "", "ARN")
Amazon Resource Name (ARN) !!

2016-11-02 05:13 UTC, dtan4 commented on command/launch.go
> +	flags.StringVar(&arn, "arn", "", "ARN")
Sorry for my insufficient explanation...
I'd like to ask you: what RESOURCE is this ARN attached to?

ex. IAM Policy ARN, IAM Instance Profile ARN

2016-11-02 06:31 UTC, koudaiii commented on command/launch.go
> +	flags.StringVar(&arn, "arn", "", "ARN")
Ooops! ok, I understand!!

https://github.com/aws/aws-sdk-go/blob/master/service/ec2/examples_test.go#L6985-L6987

```
		IamInstanceProfile: &ec2.IamInstanceProfileSpecification{
			Arn:  aws.String("String"),
			Name: aws.String("String"),
		},
```

`IAM Instance Profile ARN`

2016-11-02 08:14 UTC, dtan4 approved these changes

2016-11-02 08:14 UTC, dtan4 commented
LGTM 👍 Thanks ❗️

2016-11-02 08:14 UTC, merged